server:
    port: 8005
spring:
    application:
        name: lists-service
    datasource:
        url: jdbc:postgresql://localhost:5432/lists-test
        username: postgres
        password: weet0383
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            data-locations: classpath:sql-test/clear-lists-db.sql, classpath:sql-test/populate-lists-db.sql
eureka:
    client:
        service-url:
            defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
        fetch-registry: false
        register-with-eureka: false
    instance:
        hostname: localhost
